import { RetroUserSummary } from '../../retroachievements/types';

export const mockUserSummary: RetroUserSummary = {
  User: 'testUser',
  MemberSince: '2020-01-01',
  LastActivity: {
    ID: 123,
    timestamp: '2023-01-01',
    lastupdate: '2023-01-01',
    activitytype: 'GamePlayed',
    User: 'testUser',
    data: null,
    data2: null,
  },
  RichPresenceMsg: 'Playing Level 1',
  LastGameID: 456,
  ContribCount: 10,
  ContribYield: 5,
  TotalPoints: 1000,
  TotalSoftcorePoints: 200,
  TotalTruePoints: 800,
  Permissions: 1,
  Untracked: 0,
  ID: 789,
  UserWallActive: 1,
  Motto: 'Test Motto',
  Rank: 50,
  RecentlyPlayedCount: 1,
  RecentlyPlayed: [{
    GameID: 456,
    ConsoleID: 1,
    ConsoleName: 'NES',
    Title: 'Test Game',
    ImageIcon: '/Images/test.png',
    LastPlayed: '2023-01-01',
    MyVote: null,
    NumPossibleAchievements: 100,
    PossibleScore: 1000,
    NumAchieved: 50,
    ScoreAchieved: 500,
    NumAchievedHardcore: 30,
    ScoreAchievedHardcore: 300,
  }],
  UserPic: '/UserPic/test.png',
  TotalRanked: 1000,
  Awarded: {},
  RecentAchievements: {},
  Status: 'Online',
};

export const mockUserSummaryWithoutMottoAndRichPresence: RetroUserSummary = {
  ...mockUserSummary,
  RichPresenceMsg: '',
  Motto: '',
}; 